version: 2
jobs:
 build:
   docker:
     - image: circleci/python:3.8.1
   steps:
     - checkout
     - run: sudo chown -R circleci:circleci /usr/local/bin
     - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
     
     - restore_cache:
         key: deps-{{ checksum "Pipfile.lock" }}
     - run:
         command: |
           sudo pip install pipenv
           pipenv install
           pipenv run python -m unittest -v
     - save_cache:
         key: deps-{{ checksum "Pipfile.lock" }}
         paths:
          - ".venv"
          - "/usr/local/bin"
          - "/usr/local/lib/python3.6/site-packages"
   environment:
     PYTHONPATH: /home/circleci/project/src
 
