version: 2
jobs:
 setup_dependencies:
   docker:
     - image: circleci/python:3.8.1
   steps:
     - checkout
     - run: sudo chown -R circleci:circleci /usr/local/bin
     - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
     - restore_cache:
         key: deps-{{ checksum "Pipfile.lock" }}
     - run:
         command: |
           sudo pip install pipenv
           pipenv install
     - save_cache:
         key: deps-{{ checksum "Pipfile.lock" }}
         paths:
          - ".venv"
          - "/usr/local/bin"
          - "/usr/local/lib/python3.6/site-packages"
   environment:
     PYTHONPATH: /home/circleci/project/src
 
 
 test:
   docker:
     - image: circleci/python:3.8.1
   steps:
     - checkout
     - run: sudo chown -R circleci:circleci /usr/local/bin
     - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages     
     - restore_cache:
         key: deps-{{ checksum "Pipfile.lock" }}
     - run:
         command: |
           sudo apt install pipenv
           pipenv install
           pipenv run 
           python3 -m unittest -v
   environment:
     PYTHONPATH: /home/circleci/project/src

workflows:
  version: 2
  all:
    jobs:
      - setup_dependencies
      - test:
          requires:
            - setup_dependencies