"""
Generated By Github Copilot

プラセボCVの動作確認用テストスクリプト
"""

from module.its_analysis import ITSModelOLS, ITSModelSARIMAX, ITSModelProphet
import sys
from pathlib import Path
import pandas as pd
import statsmodels.api as sm

# モジュールのインポート
sys.path.insert(0, 'src')


print("=" * 80)
print("プラセボCV動作確認テスト")
print("=" * 80)

# テストデータの準備
print("\n[1/4] テストデータの準備...")
cigar = sm.datasets.get_rdataset("Cigar", "Ecdat").data
state = [3]
timestamp = [75, 80]

usecols = ['state', 'year', 'price', 'pop', 'sales']
cigar_model = cigar.loc[(cigar['state'].isin(state)) &
                        (cigar['year'] >= 65), usecols].copy()

print(f"  データサイズ: {cigar_model.shape}")
print(f"  介入ポイント: {timestamp}")

# OLSモデルのテスト
print("\n[2/4] OLSモデルのプラセボCVテスト...")
try:
    model_ols = ITSModelOLS(
        time_column='year',
        intervention_points=timestamp
    )

    # 通常のフィット
    model_ols.fit(cigar_model, target_column='sales')
    print("  ✅ OLSモデルのフィット成功")

    # プラセボCV実行
    placebo_results = model_ols.placebo_cross_validate(
        cigar_model,
        target_column='sales',
        n_placebo_points=3
    )

    print(f"  ✅ プラセボCV成功")
    print(f"    - プラセボ効果の平均: {placebo_results['mean_placebo_effect']:.3f}")
    print(f"    - p値: {placebo_results['p_value']:.3f}")
    print(
        f"    - モデル妥当性: {'✅ OK' if placebo_results['is_valid'] else '⚠️ 要確認'}")

except Exception as e:
    print(f"  ❌ OLSモデルのテスト失敗: {e}")
    import traceback
    traceback.print_exc()

# 複数介入プラセボCVのテスト
print("\n[3/4] 複数介入プラセボCVテスト...")
try:
    model_ols_multi = ITSModelOLS(
        time_column='year',
        intervention_points=timestamp
    )

    model_ols_multi.fit(cigar_model, target_column='sales')

    placebo_results_multi = model_ols_multi.placebo_cv_multiple_interventions(
        cigar_model,
        target_column='sales',
        n_placebo_per_intervention=2
    )

    print(f"  ✅ 複数介入プラセボCV成功")
    print(f"    - テスト回数: {len(placebo_results_multi)}")

except Exception as e:
    print(f"  ❌ 複数介入プラセボCVテスト失敗: {e}")
    import traceback
    traceback.print_exc()

# 感度分析CVのテスト
print("\n[4/4] 感度分析CVテスト...")
try:
    model_ols_sens = ITSModelOLS(
        time_column='year',
        intervention_points=timestamp
    )

    model_ols_sens.fit(cigar_model, target_column='sales')

    sensitivity_results = model_ols_sens.sensitivity_analysis_cv(
        cigar_model,
        target_column='sales',
        time_window_variations=[(5, 5), (10, 5)]
    )

    print(f"  ✅ 感度分析CV成功")
    print(f"    - テスト回数: {len(sensitivity_results)}")

except Exception as e:
    print(f"  ❌ 感度分析CVテスト失敗: {e}")
    import traceback
    traceback.print_exc()

print("\n" + "=" * 80)
print("テスト完了！")
print("=" * 80)
